// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbwj46RiTdYJrxteBb4aLWTJKTHBOxfr4',
    appId: '1:464956154250:web:f47970fdbb8f29ff9d2873',
    messagingSenderId: '464956154250',
    projectId: 'tbdetector-65a03',
    authDomain: 'tbdetector-65a03.firebaseapp.com',
    storageBucket: 'tbdetector-65a03.appspot.com',
    measurementId: 'G-9NHQPHVL2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6DMjc4RbtwePJFSxZrXnm6cwmhANXxDw',
    appId: '1:464956154250:android:25b707099eee30ee9d2873',
    messagingSenderId: '464956154250',
    projectId: 'tbdetector-65a03',
    storageBucket: 'tbdetector-65a03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGEZqTH9dlC5yxq0_vPK0HzebTA-RfLkU',
    appId: '1:464956154250:ios:ee9921796b6e1c519d2873',
    messagingSenderId: '464956154250',
    projectId: 'tbdetector-65a03',
    storageBucket: 'tbdetector-65a03.appspot.com',
    androidClientId: '464956154250-p59g5ik1c1cev9nkeqaeseo7e43r530c.apps.googleusercontent.com',
    iosClientId: '464956154250-7ejj86afvnajm2d1j3kgpt8ktm7u03p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tbdetect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGEZqTH9dlC5yxq0_vPK0HzebTA-RfLkU',
    appId: '1:464956154250:ios:cd6da8c7f51763bc9d2873',
    messagingSenderId: '464956154250',
    projectId: 'tbdetector-65a03',
    storageBucket: 'tbdetector-65a03.appspot.com',
    androidClientId: '464956154250-p59g5ik1c1cev9nkeqaeseo7e43r530c.apps.googleusercontent.com',
    iosClientId: '464956154250-j45n8cfjhmv61nvrp2dlp94m2dp705pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.tbdetect.RunnerTests',
  );
}
